// Autogenerated from Pigeon (v3.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface AMapLatLng ()
+ (AMapLatLng *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation AMapLatLng
+ (instancetype)makeWithLatitude:(NSNumber *)latitude
    longitude:(NSNumber *)longitude {
  AMapLatLng* pigeonResult = [[AMapLatLng alloc] init];
  pigeonResult.latitude = latitude;
  pigeonResult.longitude = longitude;
  return pigeonResult;
}
+ (AMapLatLng *)fromMap:(NSDictionary *)dict {
  AMapLatLng *pigeonResult = [[AMapLatLng alloc] init];
  pigeonResult.latitude = GetNullableObject(dict, @"latitude");
  NSAssert(pigeonResult.latitude != nil, @"");
  pigeonResult.longitude = GetNullableObject(dict, @"longitude");
  NSAssert(pigeonResult.longitude != nil, @"");
  return pigeonResult;
}
- (NSDictionary *)toMap {
  return @{
    @"latitude" : (self.latitude ?: [NSNull null]),
    @"longitude" : (self.longitude ?: [NSNull null]),
  };
}
@end

@interface AMapToolApiCodecReader : FlutterStandardReader
@end
@implementation AMapToolApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [AMapLatLng fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface AMapToolApiCodecWriter : FlutterStandardWriter
@end
@implementation AMapToolApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[AMapLatLng class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface AMapToolApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation AMapToolApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[AMapToolApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[AMapToolApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *AMapToolApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    AMapToolApiCodecReaderWriter *readerWriter = [[AMapToolApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void AMapToolApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AMapToolApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AMapToolApi.convertLatLng"
        binaryMessenger:binaryMessenger
        codec:AMapToolApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(convertLatLngLatLng:type:error:)], @"AMapToolApi api (%@) doesn't respond to @selector(convertLatLngLatLng:type:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        AMapLatLng *arg_latLng = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_type = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        AMapLatLng *output = [api convertLatLngLatLng:arg_latLng type:arg_type error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
